-- DDL para a tabela USERS no Firebird 2.5
-- O utilitário ISQL usa o comando 'commit'
SET TERM ^ ;

CREATE TABLE USERS (
    ID              CHAR(36)      NOT NULL,
    NAME            VARCHAR(100)  NOT NULL,
    EMAIL           VARCHAR(100)  NOT NULL,
    PASSWORD_HASH   CHAR(64)      NOT NULL
)^

ALTER TABLE USERS 
ADD CONSTRAINT PK_USERS 
PRIMARY KEY (ID)^

CREATE UNIQUE INDEX UK_USERS_EMAIL 
ON USERS (EMAIL)^

SET TERM ; ^
COMMIT;