-- Script de criação de banco de dados para Posto ABC
-- Firebird 2.5.9

-- Define a codificação UTF-8 para o script
SET NAMES UTF8;

-- Define o terminador de instrução para o caractere ^ para que os blocos BEGIN...END 
-- das Triggers e Stored Procedures possam ser executados de uma só vez.
SET TERM ^; 

-- Tabela de Tanques
CREATE TABLE TANQUES (
  ID INTEGER NOT NULL PRIMARY KEY,
  NOME VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
  TIPO VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  CAPACIDADE NUMERIC(10,2) NOT NULL,
  NIVEL_ATUAL NUMERIC(10,2) DEFAULT 0,
  DATA_REABASTECIMENTO TIMESTAMP,
  DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)^

-- Sequência para Tanques
CREATE GENERATOR GEN_TANQUES_ID^
SET GENERATOR GEN_TANQUES_ID TO 0^

-- Trigger para auto-incremento de Tanques
CREATE TRIGGER TG_TANQUES_ID BEFORE INSERT ON TANQUES
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TANQUES_ID, 1);
END^

-- Tabela de Bombas
CREATE TABLE BOMBAS (
  ID INTEGER NOT NULL PRIMARY KEY,
  NUMERO INTEGER NOT NULL,
  DESCRICAO VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  ID_TANQUE INTEGER NOT NULL,
  STATUS VARCHAR(20) CHARACTER SET UTF8 DEFAULT 'ATIVA',
  DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_TANQUE) REFERENCES TANQUES(ID)
)^

-- Sequência para Bombas
CREATE GENERATOR GEN_BOMBAS_ID^
SET GENERATOR GEN_BOMBAS_ID TO 0^

-- Trigger para auto-incremento de Bombas
CREATE TRIGGER TG_BOMBAS_ID BEFORE INSERT ON BOMBAS
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_BOMBAS_ID, 1);
END^

-- Tabela de Abastecimentos
CREATE TABLE ABASTECIMENTOS (
  ID INTEGER NOT NULL PRIMARY KEY,
  ID_BOMBA INTEGER NOT NULL,
  QUANTIDADE_LITROS NUMERIC(10,2) NOT NULL,
  VALOR_UNITARIO NUMERIC(10,2) NOT NULL,
  VALOR_ABASTECIMENTO NUMERIC(10,2) NOT NULL,
  IMPOSTO NUMERIC(10,2) NOT NULL,
  VALOR_TOTAL NUMERIC(10,2) NOT NULL,
  DATA_ABASTECIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_BOMBA) REFERENCES BOMBAS(ID)
)^

-- Sequência para Abastecimentos
CREATE GENERATOR GEN_ABASTECIMENTOS_ID^
SET GENERATOR GEN_ABASTECIMENTOS_ID TO 0^

-- Trigger para auto-incremento de Abastecimentos
CREATE TRIGGER TG_ABASTECIMENTOS_ID BEFORE INSERT ON ABASTECIMENTOS
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ABASTECIMENTOS_ID, 1);
END^

-- Reverte o terminador de instrução para o padrão (ponto e vírgula)
SET TERM ;^

-- Índices para melhorar performance
CREATE INDEX IDX_BOMBAS_TANQUE ON BOMBAS(ID_TANQUE);
CREATE INDEX IDX_ABASTECIMENTOS_BOMBA ON ABASTECIMENTOS(ID_BOMBA);
CREATE INDEX IDX_ABASTECIMENTOS_DATA ON ABASTECIMENTOS(DATA_ABASTECIMENTO);

-- Inserir tanques
INSERT INTO TANQUES (NOME, TIPO, CAPACIDADE, NIVEL_ATUAL, DATA_CRIACAO)
VALUES ('Gasolina', 'Gasolina Comum', 10000.00, 10000.00, CURRENT_TIMESTAMP);

INSERT INTO TANQUES (NOME, TIPO, CAPACIDADE, NIVEL_ATUAL, DATA_CRIACAO)
VALUES ('Óleo Diesel', 'Óleo Diesel', 12000.00, 12000.00, CURRENT_TIMESTAMP);

-- Inserir bombas para o Tanque 1 (Gasolina)
INSERT INTO BOMBAS (NUMERO, DESCRICAO, ID_TANQUE, STATUS, DATA_CRIACAO)
VALUES (1, 'BOMBA GASOLINA', 1, 'ATIVA', CURRENT_TIMESTAMP);

INSERT INTO BOMBAS (NUMERO, DESCRICAO, ID_TANQUE, STATUS, DATA_CRIACAO)
VALUES (2, 'BOMBA GASOLINA', 1, 'ATIVA', CURRENT_TIMESTAMP);

-- Inserir bombas para o Tanque 2 (Diesel)
INSERT INTO BOMBAS (NUMERO, DESCRICAO, ID_TANQUE, STATUS, DATA_CRIACAO)
VALUES (3, 'BOMBA DIESEL', 2, 'ATIVA', CURRENT_TIMESTAMP);

INSERT INTO BOMBAS (NUMERO, DESCRICAO, ID_TANQUE, STATUS, DATA_CRIACAO)
VALUES (4, 'BOMBA DIESEL', 2, 'ATIVA', CURRENT_TIMESTAMP);

-- Commit das mudanças
COMMIT;